// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCzTRgox3yrj_krTDYm7yuyh9sRQFkVsg',
    appId: '1:107630109761:android:6dfe85286fac16188492c0',
    messagingSenderId: '107630109761',
    projectId: 'chitchat-5f122',
    storageBucket: 'chitchat-5f122.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_qCdtP5UFXlAtuDtsInwh6_4uWqELLPs',
    appId: '1:107630109761:ios:10e108eec88430ae8492c0',
    messagingSenderId: '107630109761',
    projectId: 'chitchat-5f122',
    storageBucket: 'chitchat-5f122.firebasestorage.app',
    iosBundleId: 'com.example.chitchat',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyUByFI_mZZJg-1dJdqOzw0hmxB7oWgFI',
    appId: '1:107630109761:web:92411426a2b382df8492c0',
    messagingSenderId: '107630109761',
    projectId: 'chitchat-5f122',
    authDomain: 'chitchat-5f122.firebaseapp.com',
    storageBucket: 'chitchat-5f122.firebasestorage.app',
  );

}